# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   checkLinks:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 20.x
     - run: npm i -g markdown-link-check
     - run: markdown-link-check ./README.md
   buildPage:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 20.x
     - run: npm ci
     - run: npx gh-openapi-docs
     - run: bash scripts/update-ghpages.sh
